### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by bogdAAAn1**

### CODE REVIEW

**Review by SummerKatrin — APPROVED** [review]

File: app/main.py [hunk 1]
```diff
@@ -1,2 +1,98 @@
...
+        return index
+
+    @property
+    def _current_max_size(self) -> float:
+        return self._capacity * RESIZE_THRESHOLD
+
+    def _resize(self) -> None:
+        old_hash_table = self._hash_table
+        new_capacity = self._capacity * 2
+        self.__init__(new_capacity)
```
Comment (L1nk3rrr) [inline app/main.py]: bad practice of using unit at any methods

File: app/main.py [hunk 2]
```diff
@@ -1,2 +1,98 @@
...
+        if self._hash_table[index] is None:
+            raise KeyError(f"Cannot find value for key: {key}")
+        self._hash_table[index] = None
+        self._size -= 1
+
+    def __len__(self) -> int:
+        return self._size
+
+    def clear(self) -> None:
+        self.__init__()
```
Comment (L1nk3rrr) [inline app/main.py]: bad practice of using unit at any methods

File: app/main.py [hunk 3]
```diff
@@ -1,2 +1,98 @@
...
+    value: Value
+
+
 class Dictionary:
-    pass
+    def __init__(self, capacity: int = INITIAL_CAPACITY) -> None:
+        self._capacity = capacity
+        self._hash_table: list[Node | None] = [None] * self._capacity
+        self._size = 0
+        self._keys = []
```
Comment (L1nk3rrr) [inline app/main.py]: unused attr

File: app/main.py [hunk 4]
```diff
@@ -1,2 +1,98 @@
+from __future__ import annotations
+from typing import Hashable, Any, TypeAlias, Iterator
+from dataclasses import dataclass
+
+Key: TypeAlias = Hashable
+Value: TypeAlias = Any
```
Comment (L1nk3rrr) [inline app/main.py]: Such TypeAlias not helpfull, cause it's duplicate name of arg that we are waiting for.

**Review by L1nk3rrr — CHANGES_REQUESTED** [review]
Well done!
I left some comments to improve your code. Also - don't use __init__ in your methods, it's not a good practice, made logic of reset in separate method
